force-app/main/default/objects/SQX_Part__c/SQX_Part__c.object-meta.xml
<CustomObject>
    <description>This is used for CQ Assisment</description>
    <label>SQX Part</label>
    <nameField>
        <label>SQX Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SQX_Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SQX_Part__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is used for Status checked</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SQX_Part__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <description>This is used for the Part Number with unique</description>
    <label>Part Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SQX_Part__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the used to the product lookup with each part</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>SQX_Parts</relationshipLabel>
    <relationshipName>SQX_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PartSelector.cls
/**
 * @description Selector class for Part object queries (Separation of Concerns)
 * @author shalu kumari
 * @date 2025
 */
public with sharing class PartSelector {
    
    /**
     * @description Get active parts without product reference
     * @return List of parts that need product assignment
     */
    public List<SQX_Part__c> getActivePartsWithoutProduct() {
        return [
            SELECT Id, Name, Part_Number__c, Active__c, Product__c
            FROM SQX_Part__c
            WHERE Active__c = true 
            AND Product__c = null
            WITH SECURITY_ENFORCED
            ORDER BY CreatedDate
        ];
    }
    
    /**
     * @description Get parts by part numbers
     * @param partNumbers Set of part numbers to query
     * @return List of matching parts
     */
    public List<SQX_Part__c> getPartsByPartNumbers(Set<String> partNumbers) {
        return [
            SELECT Id, Name, Part_Number__c, Active__c, Product__c
            FROM SQX_Part__c
            WHERE Part_Number__c IN :partNumbers
            WITH SECURITY_ENFORCED
        ];
    }
}